name: tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: "8.1"